# Color quantization
Color quantization or color image quantization is quantization applied to color spaces; it is a process that reduces the number of distinct colors used in an image, usually with the intention that the new image should be as visually similar as possible to the original image. Color quantization is critical for displaying images with many colors on devices that can only display a limited number of colors, usually due to memory limitations, and enables efficient compression of certain types of images.

## Uniform quantization
The idea is simple, split the image into equal number of levels $N$ and map the current colors to the closest level! Easy right

In [2]:
import numpy as np
import cv2
import skimage

In [3]:
def show_images(images, titles):
    #This function is used to show image(s) with titles by sending an array of images and an array of associated titles.
    # images[0] will be drawn with the title titles[0] if exists
    # You aren't required to understand this function, use it as-is.
    assert len(images) == len(titles)
    for title in titles:
        cv2.namedWindow(title, cv2.WINDOW_NORMAL)
    
    for title, img in zip(titles, images):
        cv2.imshow(title, img)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

# How to use show_images([list of images], [list of titles]) They must have the same length
# show_images([img1, img2], ['This is image 1', 'This is image 2'])

In [4]:
def uniform_quantization(img: np.ndarray, number_of_colors: int) -> np.ndarray:
    assert number_of_colors > 1
    assert img.dtype == np.uint8
    number_of_colors -= 1
    new_img = np.round((img+1)*(number_of_colors/255)) * (255/number_of_colors)
    return new_img.astype(np.uint8)


In [5]:
img = cv2.imread('./assets/image_with_colors.png')
new_img = uniform_quantization(img, 2)
show_images([img, new_img], ['real colored image', 'new colored image'])
colors, counts = np.unique(new_img.reshape(-1, 3), return_counts = True, axis = 0)
print('number of color levels in RGB image: {}\nThe colors are:\n{}'.format(len(colors), colors))

number of color levels in RGB image: 8
The colors are:
[[  0   0   0]
 [  0   0 255]
 [  0 255   0]
 [  0 255 255]
 [255   0   0]
 [255   0 255]
 [255 255   0]
 [255 255 255]]


In [6]:
gray_img = cv2.imread('./assets/image_with_colors.png', cv2.IMREAD_GRAYSCALE)
new_gray = uniform_quantization(gray_img, 2)
show_images([gray_img, new_gray], ['real gray image', 'new gray image'])
# How many images are there in the image?
colors, counts = np.unique(new_gray.reshape(-1), return_counts = True, axis = 0)
print('number of color levels in gray image: {}\nThe colors are:\n{}'.format(len(colors), colors))

number of color levels in gray image: 2
The colors are:
[  0 255]


## Popularity algorithm
Popularity algorithms are another form of uniform quantization. However, instead of dividing the color space into constant regions these algorithms break the color space according to the density of the colors

In [6]:
def popularity_quantization(img: np.ndarray, number_of_colors: int) -> np.ndarray:
    assert number_of_colors > 1
    assert len(img.shape) == 3
               
    # Get the most popular color
    colors, counts = np.unique(img.reshape(-1, 3), return_counts = True, axis = 0)
    sorted_indicies = np.flip(np.argsort(counts))
    sorted_colors = colors[sorted_indicies]
    selected_colors = sorted_colors[:number_of_colors]
    # Get the nearest color for the pixel using Least square distance
    color_distance = np.sqrt(np.sum((np.expand_dims(img.reshape(-1, 3), axis=1) - selected_colors) ** 2, axis=2))
    indicies_of_the_least_distance = np.argmin(color_distance, axis=1)
    new_img = selected_colors[indicies_of_the_least_distance].reshape(img.shape)

    return new_img
    
    

TODO: 
* play with the value of the number of levels 
* Discuss what is the effect of number of levels? 
* Suggested values (2, 100, 150, 200)

In [11]:
#### MY CODE ####
#1-
img = cv2.imread('./assets/image_with_colors.png')
#no. of color levels is 2 
new_img = uniform_quantization(img, 2)
show_images([img, new_img], ['real colored image', 'new colored image'])
colors, counts = np.unique(new_img.reshape(-1, 3), return_counts = True, axis = 0)
print('number of color levels in RGB image: {}\nThe colors are:\n{}'.format(len(colors), colors))

##.........
gray_img = cv2.imread('./assets/image_with_colors.png', cv2.IMREAD_GRAYSCALE)
new_gray = uniform_quantization(gray_img, 2)
show_images([gray_img, new_gray], ['real gray image', 'new gray image'])
# How many images are there in the image?
colors, counts = np.unique(new_gray.reshape(-1), return_counts = True, axis = 0)
print('number of color levels in gray image: {}\nThe colors are:\n{}'.format(len(colors), colors))

number of color levels in RGB image: 8
The colors are:
[[  0   0   0]
 [  0   0 255]
 [  0 255   0]
 [  0 255 255]
 [255   0   0]
 [255   0 255]
 [255 255   0]
 [255 255 255]]
number of color levels in gray image: 2
The colors are:
[  0 255]


In [9]:
#### MY CODE ####
#2-
img = cv2.imread('./assets/image_with_colors.png')
#no. of color levels is 100 
new_img = uniform_quantization(img, 100)
show_images([img, new_img], ['real colored image', 'new colored image'])
colors, counts = np.unique(new_img.reshape(-1, 3), return_counts = True, axis = 0)
print('number of color levels in RGB image: {}\nThe colors are:\n{}'.format(len(colors), colors))

##.........
gray_img = cv2.imread('./assets/image_with_colors.png', cv2.IMREAD_GRAYSCALE)
new_gray = uniform_quantization(gray_img, 100)
show_images([gray_img, new_gray], ['real gray image', 'new gray image'])
# How many images are there in the image?
colors, counts = np.unique(new_gray.reshape(-1), return_counts = True, axis = 0)
print('number of color levels in gray image: {}\nThe colors are:\n{}'.format(len(colors), colors))

number of color levels in RGB image: 53140
The colors are:
[[  0   0   0]
 [  0   0   2]
 [  0   0   5]
 ...
 [255 255 249]
 [255 255 252]
 [255 255 255]]
number of color levels in gray image: 100
The colors are:
[  0   2   5   7  10  12  15  18  20  23  25  28  30  33  36  38  41  43
  46  48  51  54  56  59  61  64  66  69  72  74  77  79  82  85  87  90
  92  95  97 100 103 105 108 110 113 115 118 121 123 126 128 131 133 136
 139 141 144 146 149 151 154 157 159 162 164 167 170 172 175 177 180 182
 185 188 190 193 195 198 200 203 206 208 211 213 216 218 221 224 226 229
 231 234 236 239 242 244 247 249 252 255]


In [ ]:
#### MY CODE ####
#3-
img = cv2.imread('./assets/image_with_colors.png')
#no. of color levels is 2 
new_img = uniform_quantization(img, 150)
show_images([img, new_img], ['real colored image', 'new colored image'])
colors, counts = np.unique(new_img.reshape(-1, 3), return_counts = True, axis = 0)
print('number of color levels in RGB image: {}\nThe colors are:\n{}'.format(len(colors), colors))

##.........
gray_img = cv2.imread('./assets/image_with_colors.png', cv2.IMREAD_GRAYSCALE)
new_gray = uniform_quantization(gray_img, 150)
show_images([gray_img, new_gray], ['real gray image', 'new gray image'])
# How many images are there in the image?
colors, counts = np.unique(new_gray.reshape(-1), return_counts = True, axis = 0)
print('number of color levels in gray image: {}\nThe colors are:\n{}'.format(len(colors), colors))

In [12]:
#### MY CODE ####
#4-
img = cv2.imread('./assets/image_with_colors.png')
#no. of color levels is 200
new_img = uniform_quantization(img, 200)
show_images([img, new_img], ['real colored image', 'new colored image'])
colors, counts = np.unique(new_img.reshape(-1, 3), return_counts = True, axis = 0)
print('number of color levels in RGB image: {}\nThe colors are:\n{}'.format(len(colors), colors))

##.........
gray_img = cv2.imread('./assets/image_with_colors.png', cv2.IMREAD_GRAYSCALE)
new_gray = uniform_quantization(gray_img, 200)
show_images([gray_img, new_gray], ['real gray image', 'new gray image'])
# How many images are there in the image?
colors, counts = np.unique(new_gray.reshape(-1), return_counts = True, axis = 0)
print('number of color levels in gray image: {}\nThe colors are:\n{}'.format(len(colors), colors))

number of color levels in RGB image: 92552
The colors are:
[[  0   0   0]
 [  0   0   1]
 [  0   0   4]
 ...
 [255 254   0]
 [255 254 249]
 [255 255 255]]
number of color levels in gray image: 209
The colors are:
[  0   1   3   4   5   6   7   9  10  11  12  13  15  16  17  18  19  21
  22  23  24  25  27  28  29  30  32  33  34  35  36  38  39  40  41  42
  44  45  46  47  48  50  51  52  53  54  56  57  59  62  63  64  65  67
  68  69  70  71  73  74  75  76  77  79  80  81  82  83  85  86  87  88
  90  91  92  93  94  96  97  98  99 100 102 103 104 105 106 108 109 110
 111 112 115 116 117 119 120 121 122 123 125 126 127 128 129 131 132 133
 134 135 137 138 139 140 142 143 144 145 146 148 149 150 151 152 154 155
 156 157 158 160 161 162 163 164 166 167 168 169 171 172 173 174 175 177
 178 179 180 181 183 184 185 186 187 189 190 191 192 193 195 196 197 198
 200 201 202 203 204 206 207 208 209 210 212 213 214 215 216 218 219 220
 221 222 224 225 226 227 229 230 231 232 233 235 236 237 

# MY ANSWER :
QS:Discuss what is the effect of number of levels? 

When we increse number of levels for quantization ,it becomes better and image becomes clearer -- accuracy increaes when we increase quantization levels .

In [7]:
img = cv2.imread('./assets/image_with_colors.png')
img = skimage.img_as_float(img)
new = popularity_quantization(img, 2)
new = skimage.img_as_uint(new)
show_images([img, new], ['real image', 'new image'])

C:\Users\mrmah\Anaconda3\lib\site-packages\skimage\util\dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint16
  .format(dtypeobj_in, dtypeobj_out))


# Image dithering
It is possible to display a grey-level image in a bilevel device such as monochrome displays and many hardcopy printers by using a technique called image dithering. It consists of mapping the original grey image into a binary image. As our eyes perform a spatial integration, it is possible to achieve reasonable results by using a mapping strategy where the gray-intensity values are converted to density of black pixels.

If the pattern size is $n$ then the number of levels of the represented gray levels = $n^2 + 1$ as example if $n=2$ we will have a pattern of size $2 \times 2$ with $2^2 + 1 = 5$ number of gray levels
![title](./assets/dithering.png)
Now the main idea is to threshold each pixel value to it's proper representation

In [8]:
def dither_image(img: np.ndarray, positive=True) -> np.ndarray:
    assert len(img.shape) == 2
    # Create the 2x2 pattern
    if positive:
        patterns_list = np.array([[[0, 0], [0, 0]],
                                  [[0, 0], [1, 0]],
                                  [[0, 1], [1, 0]],
                                  [[0, 1], [1, 1]],
                                  [[1, 1], [1, 1]]], dtype=np.float)
    else:
        patterns_list = np.array([[[1, 1], [1, 1]],
                                  [[0, 1], [1, 1]],
                                  [[0, 1], [1, 0]],
                                  [[0, 0], [1, 0]],
                                  [[0, 0], [0, 0]]], dtype=np.float)
    
    number_of_levels = 2**2 + 1
    threshold_increment = 1/number_of_levels
    new_img = np.zeros((img.shape[0]*2, img.shape[1]*2))
    
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            for k in range(number_of_levels):
                if k*threshold_increment <= img[i, j]< (k*threshold_increment) + threshold_increment:
                    new_img[2 * i:(2 * i) + 2, 2 * j: (2 * j) + 2] = patterns_list[k]
                    break
            
    return new_img

In [9]:
img = cv2.imread('./assets/gray.png', cv2.IMREAD_GRAYSCALE)
img = skimage.img_as_float(img)
new = dither_image(img)
# The show function isn't very good with the result so we print it instead XD. Check the assets directory for the file 'out.png'
cv2.imwrite('./assets/out.png', skimage.img_as_uint(new))

True

In [14]:
def binary_to_str(binary):
    try:
        int(len(binary) / 8)
    except Exception as e:
        raise Exception('Binary length is not multiple of 8')

    string = ''

    for i in range(len(binary) // 8):
        integer = int(''.join(binary[8 * i:8 * (i + 1)]), 2)
        ascii_character = chr(integer)
        string += ascii_character

    return string

In [15]:
def decode_lsb(image_path):
    # STEP 1: Read the image
    # STEP 2: Iterate over image row by row and get pixel value
    # STEP 2.1: Get first channel value
    # STEP 2.2: read last bit (EVEN or ODD)
    # STEP 2.3: Add this bit to a list
    # STEP 2.4: call helper method (binary_to_str) to return & print ascii_string

    raise NotImplementedError('Add Your code then remove this line')

In [ ]:
secret_message = decode_lsb('./assets/secret-happy-dog.png')
    print(secret_message)